set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property PACKAGE_PIN J15 [get_ports d];
set_property PACKAGE_PIN L16 [get_ports we];
set_property PACKAGE_PIN M13 [get_ports pr_l];
set_property PACKAGE_PIN R15 [get_ports clr_l];
set_property PACKAGE_PIN H17 [get_ports q];
set_property PACKAGE_PIN K15 [get_ports qn];
set_property PACKAGE_PIN N17 [get_ports clk];
set_property IOSTANDARD LVCMOS33 [get_ports d];
set_property IOSTANDARD LVCMOS33 [get_ports we];
set_property IOSTANDARD LVCMOS33 [get_ports pr_l];
set_property IOSTANDARD LVCMOS33 [get_ports clr_l];
set_property IOSTANDARD LVCMOS33 [get_ports q];
set_property IOSTANDARD LVCMOS33 [get_ports qn];
set_property IOSTANDARD LVCMOS33 [get_ports clk];