# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado/lab_10_vga_1/lab_10_vga_1.srcs/sources_1/ip/vga_mem_1/vga_mem.xci
# IP: The module: 'vga_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado/lab_10_vga_1/lab_10_vga_1.gen/sources_1/ip/vga_mem_1/vga_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/vivado/lab_10_vga_1/lab_10_vga_1.srcs/sources_1/ip/vga_mem_1/vga_mem.xci
# IP: The module: 'vga_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado/lab_10_vga_1/lab_10_vga_1.gen/sources_1/ip/vga_mem_1/vga_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
