# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga.xdc

# IP: E:/vivado/lab_10_keyboard/lab_10_keyboard.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
