set_property PACKAGE_PIN J15 [get_ports a0]
set_property PACKAGE_PIN L16 [get_ports a1]
set_property PACKAGE_PIN M13 [get_ports a2]
set_property PACKAGE_PIN R15 [get_ports a3]
set_property PACKAGE_PIN R17 [get_ports s0]
set_property PACKAGE_PIN T18 [get_ports s1]
set_property PACKAGE_PIN H17 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports a0]
set_property IOSTANDARD LVCMOS33 [get_ports a1]
set_property IOSTANDARD LVCMOS33 [get_ports a2]
set_property IOSTANDARD LVCMOS33 [get_ports a3]
set_property IOSTANDARD LVCMOS33 [get_ports s0]
set_property IOSTANDARD LVCMOS33 [get_ports s1]
set_property IOSTANDARD LVCMOS33 [get_ports y]


