set_property SRC_FILE_INFO {cfile:E:/vivado/lab_0/lab_0.srcs/constrs_1/new/my_first_fpga.xdc rfile:../../../lab_0.srcs/constrs_1/new/my_first_fpga.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports A]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports B]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports F]
